# Image file gpu
FROM yashikab/gputensorflow:latest

LABEL Yashio Kabashima

# add configuration files
ADD ./src/gpu_settings/requirements.txt /root/requirements.txt

# install required pip packages
# upgrade pip
ENV pip /root/.pyenv/shims/pip
RUN $pip install -r requirements.txt


# set to home directory
WORKDIR /root/